### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by m1e1w1** [metabrainz/musicbrainz-vm#1]
Hello,

I installed virtualbox for windows, installed vagrant for windows, then cloned the musicbrainz repository.

I ran the CMD: vagrant up inside the folder musicbrainz-vm-master, which created a .vagrant folder, built the VM.

I ran vagrant ssh -- bin/set-token and replaced <token> with my token (also removed both < and > so it was just my token without those.

I ran vagrant ssh -- bin/replicate

How do i access musicbrainz? 

In the VM, i changed my network connection 1 from NAT to Bridged, and got a local IP. going to local IP such as 192.168.1.50:5000 shows nothing. same with 192.168.1.50:8080

what am i missing? Thanks.

**Comment by mayhem** [comment]
Are you on IRC? I'd love to chat with you about this. IRC network freenode, channel #metabrainz. I'm user ruaok.

**Comment by m1e1w1** [comment]
I'll go log in.

**Comment by mayhem** [comment]
Usage has now been added to README.

**Comment by mayhem** [comment]
There is a test VM here: ftp://ftp.eu.metabrainz.org/pub/musicbrainz-vm/
